name: CI/CD

on:
  push:
    branches:
      - development-stagging-v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the branch name
        id: branch
        run: echo ::set-output name=branch::${{ github.ref }}

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: 43.204.200.105
          username: centos
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            MIIJKAIBAAKCAgEA6hY8IwjYb4x4Gy+dJV/0oKc58F7xb9S1pnsrOGsLqlpCGdQe
            3MNWYQmEnVzzumyXQDb9PvTJc3GN4DabLmNVrYiNq5UKvITnSIl6oHp9cdgC4STt
            WGxwQ1lRCnHOisOfvE6cEdw3gu2OMz2qfPVSMa2oF1NyT0YQbgIcTtQJIEhxUA2S
            amJkeZteZoMbJ0hjC8E2iS4Prvb2P79DeG1FNdzUIP4ovY33jU+VmfMT51E1BlmP
            MqDj7OKw5VKFWoO9ZaHFTqBnKiCRuC5C7aIeGybHn22nKZi9Ew3qvlGaYGw9CFqi
            ksuny7imHxk4y2jveWubX3/InvpghaosT9SCaOdaJIGqsNKwQRQ9g528C7RlIvT1
            GyEPTRk0SIr3nBji0nr+eDprgysmkonlXh9RY4VEB1OmGY/ovBFS6GDBIwWNBJWG
            1RBWOJkzcnYLTYWpXUlKGrskm1x+R4sRheOn4VWV2qqQwksCO0RkTXymMi0U75Bq
            FzmUFaL6CreK/oggUqM/oTY51A2j0h8ico+/MsiY8XnXtYnLX4L7lDOKCq9KaDBZ
            32ani0kW9zlVLYdq4FMBpdrKDf0l432OnFFMhgZ15bVt0sAoeea0EuHr6J654uvo
            diA+KZke/L86b2Ys2DsEPcnG7U6HiQP1rhEkyAWWszclNeP3yaPArKYbtrsCAwEA
            AQKCAgArVy6PNgYMsS9TqT8pOljqncuma428LN/tEQTxjzA7vDZc3d9Q9IG7ua1q
            DVm6/HwMkaHV1DCwRSgFiVa2AgJM/OluCUxRlzHTRlEEAWnUeDAgS1v+cSVf8tuE
            WYnqO0oJ7WwMCn/kp+MaLaKxPCKZvBNRLkwNzWUhWRawqaV+6qrALaMcO1drBI83
            37JZVZexB3b3cyXIOUVijCEL3P9hd5929FfKsMxSx5dlR5I509lDcbWHpC5PH7Gs
            49h458dbV9ZWNnCjZiBUv4v4v3lfgZCYPg8jLnpjWsJJtoYksCWktFNBZp+MooVv
            YJYZYzZjfr7nsZsNhEH2vYkyxp/WPcOLWSoiHp63NEMIE2Ll+1seihv2btRWedM9
            NKFm0bLspbUJhMyUAeOfYgT1cC3wLlWCqGVn6k+blKeHpa40z8vDNdpPLbRnrCay
            OsXSn1W4ZjOOwqWDb/MugQ+ut/yqd1smJJIKmw5U+837urFkIuBjyDq02+fAfIAv
            dxkNVdUNFuU8C3Mz9iNlsAq+VarF6zgCxeX5B5xXMYuLR0Lc9oRD/rALi/1tYpWo
            dJbwg0Up+YMBASJ+pDy862RhF0GcsL37/CkWJdECi+iTm2DNw55QOXokHHvrm6T3
            bUEG12nGsIHjrDKtDwE6nOCrsDdOn4mfL5OgOFDQpWy27xmzEQKCAQEA+lg/HQpJ
            QXIQ37xRlKBZ2QTlSTf1Xud9TA6CHKvfBiQFJnxrxGpjUAyhttEtQjKORdAIXy67
            EfMh6jvQHD4zZIVMCVasoCrGRZyuDbOM2oPAkL/9ibWSi9SbRc3ArXY/diPSIL3v
            IzN8OFLhvMkaHBOUCmtqQXbWpngARmsoZgb1Jo6w7jYHLem1j2R8g8qtGNBXv6jJ
            yjAKKRBvlwS9yqvP9QzXLdhXfQeVqUT5tF4ozTLBxh2OSdpD2cwd4e83vn9mZZtb
            BsFr+XsfW1JjF1zbNXznRb6Jvm6mRtHsY2Kcg4p/2ZffcUdaGAb2v2SyKNJL0aXw
            EON/uztSVZzDtQKCAQEA71/38bJv5/qt4oONIHbEFHxCyvPyr2eKo7e1IimSY+9R
            z4O16+WC9pQR3wNS+dOXQcfGdQjaQeIRZEAPbFjbVTwmDZHRmXzlopIzuwCshFHh
            gEs49BNiUrI6ogx067CL+RDzve5aiaOfJPw01sCNaAsiCkRxq/BB5HwMvE5I2BR+
            RiryttYH1b19qkYeNUiKyt/kf+VFK2MnfLbYbnuBm7jUVxCPoGD1
            -----END OPENSSH PRIVATE KEY-----
          port: 22
          script: |
            cd /var/www/dev-siram-workstation.co.id
            git stash
            git checkout ${{ steps.branch.outputs.branch }}
            git pull origin ${{ steps.branch.outputs.branch }}
